name: Upload static files to s3
on:
  push:
    branches:
      - main

jobs:
  upload-to-s3:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "15"
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
      - run: yarn
      - run: yarn build
        env:
          REACT_APP_BACKEND_URL: http://165.232.172.90
      - name: Publish to s3 bucket
        run: |
          # Install aws cli https://github.com/aws/aws-cli/issues/5262
          sudo apt-get install python3-setuptools
          python3 -m pip install --user awscli

          aws s3 cp --recursive build s3://todo-jack --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
